version: '3'
services:
  app:
    build: .
    volumes:
      - ".:/app"
    ports:
      - 3000:${NODE_PORT}
    depends_on:
      - redis
    environment:
      PORT: ${NODE_PORT}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: redis
    command: npm run start
  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis
    command: redis-server
    ports: 
      - 6379:${REDIS_PORT}
    environment:
      PORT: ${REDIS_PORT}